sudo: false
dist: trusty
language: php

php:
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION=5.4.*
  - LARAVEL_VERSION=5.5.*
  - LARAVEL_VERSION=5.6.*
  - LARAVEL_VERSION=5.7.*
  - LARAVEL_VERSION=5.8.*

matrix:
  exclude:
    - php: 5.6
      env: LARAVEL_VERSION=5.5.*
    - php: 5.6
      env: LARAVEL_VERSION=5.6.*
    - php: 5.6
      env: LARAVEL_VERSION=5.7.*
    - php: 5.6
      env: LARAVEL_VERSION=5.8.*
    - php: 7.0
      env: LARAVEL_VERSION=5.6.*
    - php: 7.0
      env: LARAVEL_VERSION=5.7.*
    - php: 7.0
      env: LARAVEL_VERSION=5.8.*

before_script:
  - travis_retry composer self-update
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require "illuminate/filesystem:${LARAVEL_VERSION}" --no-update; fi;
  - travis_retry composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
