sudo: false
dist: trusty
language: php

php:
  - 5.6
  - 7
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION=5.4.*
  - LARAVEL_VERSION=5.5.*
  - LARAVEL_VERSION=5.6.*
  - LARAVEL_VERSION=5.7.*

matrix:
  exclude:
    - php: 5.6
      env: LARAVEL_VERSION=5.5.*
    - php: 5.6
      env: LARAVEL_VERSION=5.6.*
    - php: 5.6
      env: LARAVEL_VERSION=5.7.*
    - php: 7.0
      env: LARAVEL_VERSION=5.6.*
    - php: 7.0
      env: LARAVEL_VERSION=5.7.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "illuminate/filesystem:${LARAVEL_VERSION}" --no-update; fi;
  - composer update

script:
  - vendor/bin/phpunit
  